### PR TITLE
2.7 all in one commit

### PR DESCRIPTION
**Pull request by stonedDiscord**
Cortana, damage report

### CODE REVIEW

**Comment by oldmud0** [comment]
most of it is unnecessary aov stuff.

the only thing potentially relevant to 2.7 is this line:
https://github.com/AttorneyOnline/tsuserver3/blob/1daa6d3292ea78f5adf81f62a44b5f823363d7fe/server/tsuserver.py#L229

**Comment by cents02** [comment]
> most of it is unnecessary aov stuff.
> 
> the only thing potentially relevant to 2.7 is this line:
> https://github.com/AttorneyOnline/tsuserver3/blob/1daa6d3292ea78f5adf81f62a44b5f823363d7fe/server/tsuserver.py#L229

Well we do need to change the packet checking as well, since there additional parameters introduced for the shaking and what not.

**Comment by oldmud0** [comment]
oh yeah, and that. but this PR is mixed with a number of extra features that need to be moved to separate branches and reviewed separately.

**Comment by cents02** [comment]
This PR is unecessary, please see #95

**Pull request closed without merging**
