### PR TITLE
Changed zalgo filter to an editable string

### PR DESCRIPTION
**Pull request by Enovale**
According to @oldmud0 's request.

### CODE REVIEW

**Review by oldmud0 — CHANGES_REQUESTED** [review]
You don't need to use bytes to use Unicode escape sequences.

**Comment by Enovale** [comment]
I can't find any way to do it otherwise...

**Comment by oldmud0** [comment]
How about that?

**Comment by Enovale** [comment]
Seems to work fine, lol

Well, it's not my call to merge it :P

**Pull request merged**
