### PR TITLE
Random bunch of changes made to vanilla

### PR DESCRIPTION
**Pull request by oldmud0**

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
Uh any of this worth porting to kfo-server?

**Comment by stonedDiscord** [comment]
I think I've seen the /delay command before and it's already merged

**Comment by stonedDiscord** [comment]
nevermind forgot to PR

**Review by stonedDiscord — APPROVED** [review]
py3.8 and /delay

**Comment by oldmud0** [comment]
Diff was misleading. Thanks github

**Pull request merged**
